### ISSUE TITLE
Update request for Dead cells new buildId[e01bb880d1bae5a5]

### ISSUE THREAD

**Issue by Tairraos** [MentalBlank/SXOS-CheatDB#3]
Hi MentalBlank

I just checked out github sxos-cheatdb, and tried your newest updated the game "dead cells" which is titleiId is "0100fc000aef0000" one. It not match the latest update. after updated, the buildId became “e01bb880d1bae5a5”. Could you update a new cheat txt into?
( update file name is: Dead Cells [UPD][0100646009fbe800][v65536].nsp )

And could you give me some advice how to find the address pointer from "dead cells", i'd like to learn how to make cheat, but i tried a lot of times, still can't make a valid cheat txt, it is really upset me.

Thanks.

**Comment by MentalBlank** [comment]
Hi Tairraos, What version of the game are you using?
To use the current Dead Cell's cheats you will need version 1.0.2 of the game
(Dead Cells [UPD][0100fc000aef0800][v131072].nsp)

I'll have a look later for codes for your update but if you have a look on the request thread on GBATemp there is some useful programs and posts written on how to find codes.
I recommend following the guide posted there using Noexs and the SXOS code converter and also reading the official guide by Team Xecuter.

**Comment by Tairraos** [comment]
Thanks MentalBlank. i just saw it but you already updated.

**Comment by Tairraos** [comment]
Dead Cells v1.0.2
Title ID: 0100fc000aef0000
Build ID: e01bb880d1bae5a5

**Comment by Tairraos** [comment]
I already read the official guide(also the relative post on GBATemp) , but still not get the point how to get dynamic pointer. I can lock HP/Gold when Dead cells running, but after restart the game, code will invalid...

Anyway, i will go through the post again to find something missed.

Thanks.
